FROM ubuntu:18.04 

RUN apt-get update && apt-get install -y git xsdcxx libxerces-c-dev libgsl-dev libboost-all-dev cmake python3-pip python3-gdbm libzmq3-dev wget curl tmux nano

RUN pip3 install torch torchvision jupyter 
RUN cd /code && git clone --branch master https://github.com/probprog/pyprob_cpp.git && cd pyprob_cpp && mkdir build && cd build && cmake ../src && cmake --build . && make install
RUN cd /code && git clone https://github.com/probprog/pyprob.git && cd pyprob && pip3 install .

